export const All = [
  {
    id: "1",
    title: "Give Away",
    img: "assets/eco.jpeg",
    video: "assets/giveaway.webm",
    desc: " It is a full-stack shopping web application where all variety of products are available.Here we have an admin page for organizing orders and adding products.",
    tec: ["Node js ", " MongoDB ", " React", " Redux", " Express "],
    category: "Full Stack",
    // demo: "https://giveawayapp153.herokuapp.com/",
  },
  {
    id: "2",
    title: "Student Service",
    img: "assets/studentservice.jpg",
    video: "assets/studentservice.webm",
    desc: " Developed for students, this is similar to Quora where questions are asked and answers can be posted.Used firebase for authentication,storage and deployed on heroku",
    tec: [" React", " Redux", " Firebase"],
    category: "React",
    // demo: "http://cbitstudentservice.herokuapp.com/",
  },
  {
    id: "3",
    title: "Done With It",
    img: "assets/done.jpg",
    video: "working",
    desc: " This is an app where used products can be sold and bought with ease.The idea is similar to olx but the products sometimes are sold without charging i.e for free",
    tec: [" React Native", " Firebase"],
    category: "React",
  },

  {
    id: "4",
    title: "Signal clone",
    img: "assets/chat.jpg",
    video: "assets/signal.webm",
    desc: " This is a chatting application which is similar to signal app where users can join the groups and start their conversation.Used firebase for authentication,storage and deployment.",
    tec: [" React Native", " Firebase"],
    category: "React",
    demo: "https://signal-clone-7f371.web.app/",
  },
  {
    id: "5",
    title: "Student Recommendation",
    img: "assets/recommendation.png",
    video: "assets/recommendation.webm",
    desc: "An application which recommends courses,books and internships for students.Recommendations are given based on the user priorities",
    tec: ["Python ", " Machine Learning", " React", " Redux", " Firebase "],
    category: "Others",
    // demo: "https://share.streamlit.io/baludeshamoni/student_recommendations/main/student_Recommendations.py",
  },
  {
    id: "6",
    title: "Rise Of Devs",
    icon: "./assets/globe.png",
    img: "./assets/dev.png",
    video: "no",
    desc: "  A MERN-stack web application which is a platform for the developers all around the world.Users can post their idea , can also view and comment on other developers ideas.",
    tec: ["Node js ", " MongoDB ", " React", " Redux", " Express "],
    category: "Full Stack",
    // demo: "http://riseofdevs.herokuapp.com/post",
  },
];
